pipeline:
  sftp_cache_restore:
    image: appleboy/drone-sftp-cache
    server: rancher.seattleslow.com
    port: 22
    username: rancher
    secrets: [ sftp_cache_private_key ]
    path: /home/rancher/drone
    restore: true
    mount: [tmp, dl, feeds, feeds.conf, files, Macondo]
    when:
      local: false
      event: [ push ]

  initial_build_ar7xx:
    image: josmo/nyc-mesh-cooker
    commands:
      - env
      - ./cooker -b ar71xx/generic -j6
  cook_ubnt-m-xm:
    image: josmo/nyc-mesh-cooker
    commands:
      - ./cooker -c ar71xx/generic --profile=ubnt-nano-m-xw --flavor=qmp_nyc
      - tar -cvf ubnt-nano-m-xw.tar output/ar71xx/generic/ubnt-nano-m-xw/

  publish_ubnt-m-xm:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ubnt-nano-m-xw.tar
    checksum:
      - md5
      - sha1
      - sha256
    draft: true
    when:
      event: tag

  sftp_cache_build:
    image: appleboy/drone-sftp-cache
    server: rancher.seattleslow.com
    port: 22
    username: rancher
    secrets: [ sftp_cache_private_key ]
    path: /home/rancher/drone
    rebuild: true
    mount: [tmp, dl, feeds, feeds.conf, files, Macondo]
    when:
      local: false
      event: [ push ]
